POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "fullname":"Piyu Shah",
  "username":"Piyu",
  "password":"123456",
  "confirmpassword":"123456",
  "gender":"female"
}

###
POST http://localhost:5000/api/auth/login
Content-Type:application/json

{
    "username":"John Doe",
    "password":"123456"
}